wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.5
    cli_version: 0.16.2
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1731064910.318996
    t:
      1:
      - 1
      - 9
      - 41
      - 55
      - 77
      - 103
      2:
      - 1
      - 9
      - 41
      - 55
      - 77
      - 103
      3:
      - 13
      - 23
      4: 3.11.5
      5: 0.16.2
      8:
      - 3
      - 5
      13: windows-amd64
name:
  desc: null
  value: Hybrid-GNN
project:
  desc: null
  value: tester
train:
  desc: null
  value: false
n_hidden:
  desc: null
  value: 2
dim_hidden:
  desc: null
  value: 250
passes:
  desc: null
  value: 12
seed:
  desc: null
  value: 1
lr:
  desc: null
  value: 0.0001
att_radius:
  desc: null
  value: .inf
noise_var:
  desc: null
  value:
  - 0.001
  - 0.01
batch_size:
  desc: null
  value: 8
lambda_d:
  desc: null
  value: 5.0
max_epoch:
  desc: null
  value: 6000
pretrained:
  desc: null
  value: false
plot_rollout:
  desc: null
  value: false
node:
  desc: null
  value: 0
